//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryComettoBuscarArchivo.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pryComettoBuscarArchivo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1,	EL SISTEMA OPERATIVO,	7,	1,	6
        ///2,	LA TEORIA DE LA RELATIVIDAD,	6,	3,	6
        ///3,	FUNCIONAMIENTO DEL CORAZON,	5,	5,	1
        ///4,	LAS ABEJAS DEL CAMPO,	4,	7,	1
        ///5,	EL DERECHO ROMANO,	3,	1,	5
        ///6,	LAS TAREAS DEL HIGADO,	2,	3,	5
        ///7,	EL LENGUAJE JAVASCRIPT,	1,	5,	4
        ///8,	APRENDIENDO C EN 21 DIAS,	7,	7,	4
        ///9,	LAS REDES LOCALES,	6,	2,	7
        ///10,	DERIVADAS E INTEGRALES,	5,	4,	7
        ///11,	PLATON Y EL PENSAMIENTO,	4,	6,	7
        ///12,	LOS COHETES DE HELIO,	3,	2,	3
        ///13,	EL SISTEMA PLANETARIO,	2,	4,	3
        ///14,	LAS FUNCIONES DEL FISCAL,	1,	6,	2
        ///15,	LA  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string LIBRO {
            get {
                return ResourceManager.GetString("LIBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon libros {
            get {
                object obj = ResourceManager.GetObject("libros", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
